---
- hosts: local
  tasks:
  - name: Set bin directory
    set_fact:
      bin_folder: "{{general_software_base}}/bin"
  - name: Check if kn is already installed
    stat:
      path: "{{bin_folder}}/kn"
    register: is_installed

  - name: Install kn
    block:
    - name: Download kn
      get_url:
        url: "https://mirror.openshift.com/pub/openshift-v4/clients/serverless/{{knative_client_version}}/kn-linux-amd64-{{knative_client_version}}.tar.gz"
        dest: "~/.ansible/tmp/kn-linux-amd64-{{knative_client_version}}.tar.gz"
      when: not is_installed.stat.exists

    - name: Unarchive kn binaries
      unarchive:
        src: "~/.ansible/tmp/kn-linux-amd64-{{knative_client_version}}.tar.gz"
        dest: "{{bin_folder}}"
        exclude:
          - "LICENSE"
        mode: '0700'
      when: not is_installed.stat.exists

    - name: Clean downloaded files
      file:
        state: absent
        path: "~/.ansible/tmp/kn-linux-amd64-{{knative_client_version}}.tar.gz"