---
- hosts: local
  tasks:
  - name: Set bin directory
    set_fact:
      bin_folder: "{{general_software_base}}/bin"
  - name: Download kubectl
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/{{minikube_kubernetes_version}}/bin/linux/amd64/kubectl
      dest: "{{bin_folder}}/kubectl"
      mode: '0700'
  - name: Download minikube
    get_url:
      url: https://storage.googleapis.com/minikube/releases/v{{minikube_version}}/minikube-linux-amd64
      dest: "{{bin_folder}}/minikube"
      mode: '0700'
