---
- hosts: local
  tasks:
  - name: Create a minikube home
    file:
      path: "{{minikube_home}}"
      state: directory
  - name: Create a kubeconfig directory
    file:
      path: "{{minikube_home}}/.kube"
      state: directory
  - name: Create a helm home
    file:
      path: "{{minikube_helm_home}}"
      state: directory
  - name: Update symbolic link
    file:
      src: "{{minikube_home}}/.kube"
      dest: "{{general_home}}/.kube"
      state: link
  - name: Generate envorinment variables
    template:
      src: minikube-setenv.sh.j2
      dest: setenv.sh
      mode: '0700'