kamel:
  install:
    #kits: '[js,yaml,java,kotlin,groovy,knative]'
    kits:
      - js
      - yaml
      - java
      - kotlin
      - groovy
      - knative
    maven-settings: configmap:camel-k-maven-settings/settings.xml
    olm: false
